Repository Coffee-Commit/Crema_Backend, pull requests merged in 2025-09, with the labels that each got.

#57 [feat] dev 서버 debug용 controller 구현
  src/main/java/coffeandcommit/crema/global/auth/controller/DebugController.java
Labels: 기능 개발

#58 [fix] dev 서버 OAuth2 로그인 후 리다이렉트 시 401 에러 해결
  src/main/resources/application-prod.yml
Labels: 버그, 기능 개발

#56 가이드 커피챗 주제 등록/조회/삭제 기능
  src/main/java/coffeandcommit/crema/domain/globalTag/dto/JobFieldDTO.java
  src/main/java/coffeandcommit/crema/domain/globalTag/dto/TopicDTO.java
  src/main/java/coffeandcommit/crema/domain/globalTag/entity/JobField.java
  src/main/java/coffeandcommit/crema/domain/globalTag/enums/ChatTopicType.java
  src/main/java/coffeandcommit/crema/domain/globalTag/enums/JobNameType.java
  src/main/java/coffeandcommit/crema/domain/globalTag/enums/JobType.java
  src/main/java/coffeandcommit/crema/domain/globalTag/enums/TopicNameType.java
  src/main/java/coffeandcommit/crema/domain/globalTag/repository/ChatTopicRepository.java
  src/main/java/coffeandcommit/crema/domain/globalTag/repository/JobFieldRepository.java
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideController.java
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideMeController.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/request/GuideChatTopicRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/request/GuideJobFieldRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideChatTopicResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideJobFieldResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/GuideChatTopic.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/GuideJobField.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/GuideChatTopicRepository.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideMeService.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideService.java
  src/main/java/coffeandcommit/crema/domain/member/entity/MemberJobField.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideMeServiceTest.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideServiceTest.java
Labels: 기능 개발

#65 가이드 스케줄 관련 기능 구현
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideController.java
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideMeController.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/request/GuideScheduleRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/request/ScheduleRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/request/TimeSlotRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideScheduleResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/ScheduleResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/TimeSlotResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/GuideSchedule.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/TimeSlot.java
  src/main/java/coffeandcommit/crema/domain/guide/enums/DayType.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/GuideScheduleRepository.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/TimeSlotRepository.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideMeService.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideService.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideMeServiceTest.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideServiceTest.java
Labels: 기능 개발

#72 fix: OAuth2 로그인 후 리다이렉트 uri 수정
  src/main/java/coffeandcommit/crema/global/auth/config/SecurityConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: 버그

#74 Feature/#70 guide experiences
  src/main/java/coffeandcommit/crema/domain/globalTag/dto/TopicDTO.java
  src/main/java/coffeandcommit/crema/domain/globalTag/entity/ChatTopic.java
  src/main/java/coffeandcommit/crema/domain/globalTag/enums/ChatTopicType.java
  src/main/java/coffeandcommit/crema/domain/globalTag/repository/ChatTopicRepository.java
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideController.java
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideMeController.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/request/GroupRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/request/GuideExperienceDetailRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/request/GuideExperienceRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GroupResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideChatTopicResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideExperienceDetailResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideExperienceResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/ExperienceGroup.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/GuideChatTopic.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/ExperienceDetailRepository.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/ExperienceGroupRepository.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideMeService.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideService.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideMeServiceTest.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideServiceTest.java
Labels: 기능 개발

#77 Feature/#75 review post
  src/main/java/coffeandcommit/crema/domain/reservation/repository/ReservationRepository.java
  src/main/java/coffeandcommit/crema/domain/reservation/service/ReservationService.java
  src/main/java/coffeandcommit/crema/domain/review/controller/ReviewController.java
  src/main/java/coffeandcommit/crema/domain/review/dto/request/ExperienceEvaluationRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/review/dto/request/ReviewRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/review/dto/response/ExperienceEvaluationResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/review/dto/response/ReviewResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/review/entity/Review.java
  src/main/java/coffeandcommit/crema/domain/review/entity/ReviewExperience.java
  src/main/java/coffeandcommit/crema/domain/review/repository/ReviewRepository.java
  src/main/java/coffeandcommit/crema/domain/review/service/ReviewService.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/test/java/coffeandcommit/crema/domain/reservation/service/ReservationServiceTest.java
  src/test/java/coffeandcommit/crema/domain/review/service/ReviewServiceTest.java
Labels: 기능 개발

#84 Feature/#82 reservation get
  src/main/java/coffeandcommit/crema/domain/globalTag/dto/TopicDTO.java
  src/main/java/coffeandcommit/crema/domain/globalTag/enums/JobNameType.java
  src/main/java/coffeandcommit/crema/domain/globalTag/enums/TopicNameType.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideChatTopicResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideJobFieldResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/Guide.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/GuideJobField.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/GuideRepository.java
  src/main/java/coffeandcommit/crema/domain/member/entity/Member.java
  src/main/java/coffeandcommit/crema/domain/reservation/controller/ReservationController.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/request/ReservationDecisionRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/CoffeeChatSummaryResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/GuideDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/GuideSurveyResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/MemberChatTopicResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/MemberDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/MemberJobFieldResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/ReservationApplyResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/ReservationDecisionResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/ReservationSurveyResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/entity/Reservation.java
  src/main/java/coffeandcommit/crema/domain/reservation/repository/ReservationRepository.java
  src/main/java/coffeandcommit/crema/domain/reservation/service/ReservationService.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/test/java/coffeandcommit/crema/domain/reservation/service/ReservationServiceTest.java
Labels: 기능 개발

#87 내가 작성한 리뷰 조회 기능 구현
  src/main/java/coffeandcommit/crema/domain/reservation/repository/ReservationRepository.java
  src/main/java/coffeandcommit/crema/domain/review/controller/ReviewController.java
  src/main/java/coffeandcommit/crema/domain/review/dto/response/GuideInfo.java
  src/main/java/coffeandcommit/crema/domain/review/dto/response/MyReviewResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/review/dto/response/ReservationInfo.java
  src/main/java/coffeandcommit/crema/domain/review/dto/response/ReviewInfo.java
  src/main/java/coffeandcommit/crema/domain/review/repository/ReviewRepository.java
  src/main/java/coffeandcommit/crema/domain/review/service/ReviewService.java
  src/test/java/coffeandcommit/crema/domain/review/service/ReviewServiceTest.java
Labels: 기능 개발

#88 가이드 커피챗 등록 및 조회 기능 구현
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideController.java
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideMeController.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/request/GuideCoffeeChatRequestDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideCoffeeChatResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/Guide.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideMeService.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideService.java
  src/main/java/coffeandcommit/crema/domain/review/repository/ReviewRepository.java
  src/main/java/coffeandcommit/crema/global/auth/controller/TestAuthController.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideMeServiceTest.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideServiceTest.java
Labels: 기능 개발

#89 [Feat] 멤버에서 가이드 승격 로직 구현 + guide 도메인 리팩토링
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideMeController.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/Guide.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideMeService.java
  src/main/java/coffeandcommit/crema/domain/member/controller/MemberController.java
  src/main/java/coffeandcommit/crema/domain/member/dto/request/MemberUpgradeRequest.java
  src/main/java/coffeandcommit/crema/domain/member/dto/response/MemberUpgradeResponse.java
  src/main/java/coffeandcommit/crema/domain/member/entity/Member.java
  src/main/java/coffeandcommit/crema/domain/member/service/MemberService.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideMeServiceTest.java
Labels: 리팩토링, 기능 개발

#93 가이드 관련 조회 기능 구현
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideController.java
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideMeController.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/CoffeeChatStatsResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideExperienceEvaluationResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuidePendingReservationResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideProfileResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideReviewResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/GuideThisWeekCoffeeChatResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/MemberInfo.java
  src/main/java/coffeandcommit/crema/domain/guide/dto/response/TimeSlotResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/guide/enums/DayType.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/ExperienceGroupRepository.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideMeService.java
  src/main/java/coffeandcommit/crema/domain/guide/service/GuideService.java
  src/main/java/coffeandcommit/crema/domain/reservation/controller/ReservationController.java
  src/main/java/coffeandcommit/crema/domain/reservation/dto/response/ReservationCompletionResponseDTO.java
  src/main/java/coffeandcommit/crema/domain/reservation/repository/ReservationRepository.java
  src/main/java/coffeandcommit/crema/domain/reservation/service/ReservationService.java
  src/main/java/coffeandcommit/crema/domain/review/repository/ReviewExperienceRepository.java
  src/main/java/coffeandcommit/crema/domain/review/repository/ReviewRepository.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideMeServiceTest.java
  src/test/java/coffeandcommit/crema/domain/guide/service/GuideServiceTest.java
  src/test/java/coffeandcommit/crema/domain/reservation/service/ReservationServiceTest.java
Labels: 기능 개발

#92 [Fix] 빌드 테스트 오류 수정 (Jenkins)
  Jenkinsfile
Labels: 버그

#96 [Feat] 멤버 도메인 관심직무/내 커피챗 조회 구현 + pdf 업로드/멤버 프로필사진 업로드 로직 연동
  src/main/java/coffeandcommit/crema/domain/member/controller/MemberCoffeeChatController.java
  src/main/java/coffeandcommit/crema/domain/member/controller/MemberController.java
  src/main/java/coffeandcommit/crema/domain/member/dto/request/MemberChatTopicRequest.java
  src/main/java/coffeandcommit/crema/domain/member/dto/request/MemberJobFieldRequest.java
  src/main/java/coffeandcommit/crema/domain/member/dto/request/MemberUpgradeRequest.java
  src/main/java/coffeandcommit/crema/domain/member/dto/response/MemberChatTopicResponse.java
  src/main/java/coffeandcommit/crema/domain/member/dto/response/MemberCoffeeChatResponse.java
  src/main/java/coffeandcommit/crema/domain/member/dto/response/MemberJobFieldResponse.java
  src/main/java/coffeandcommit/crema/domain/member/dto/response/MemberUpgradeResponse.java
  src/main/java/coffeandcommit/crema/domain/member/service/MemberCoffeeChatService.java
  src/main/java/coffeandcommit/crema/domain/member/service/MemberProfileService.java
  src/main/java/coffeandcommit/crema/domain/member/service/MemberService.java
  src/main/java/coffeandcommit/crema/domain/reservation/repository/ReservationRepository.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
Labels: 기능 개발

#102 [fix] 프론트엔드와 oauth2 연동을 위해 spring security 변경
  src/main/java/coffeandcommit/crema/global/auth/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 버그

#105 사전자료 조회 테스트 불가 해결
  mock/init-dummy.json
  src/main/java/coffeandcommit/crema/domain/reservation/entity/Survey.java
  src/main/resources/init.sql
Labels: 버그, 리팩토링

#107 [feat] test auth 도메인 dev 프로필에서 사용 가능하게 변경
  src/main/java/coffeandcommit/crema/global/auth/controller/TestAuthController.java
Labels: 기능 개발

#119 [fix] spring security 파일 롤백
  load-test-logs.txt
  member-load-test(yes-reservation).js
  member-load-test.js
  results.json
  src/main/java/coffeandcommit/crema/global/auth/config/SecurityConfig.java
Labels: 버그

#127 [fix] 멤버에서 가이드 업그레이드 로직, 프론트에서 연동 시 500 에러 발생
  src/main/java/coffeandcommit/crema/global/auth/config/SecurityConfig.java
Labels: 버그

#152 querydsl 도입으로 성능 개선
  mock/front-dummy.json
  src/main/java/coffeandcommit/crema/domain/guide/controller/GuideController.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/GuideRepository.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/GuideRepositoryCustom.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/GuideRepositoryImpl.java
  src/main/java/coffeandcommit/crema/domain/guide/repository/GuideWithStats.java
  src/main/java/coffeandcommit/crema/domain/reservation/repository/ReservationRepository.java
  src/main/java/coffeandcommit/crema/domain/reservation/repository/ReservationRepositoryCustom.java
  src/main/java/coffeandcommit/crema/domain/reservation/repository/ReservationRepositoryImpl.java
  src/main/java/coffeandcommit/crema/domain/review/controller/ReviewController.java
  src/main/java/coffeandcommit/crema/domain/review/enums/ReviewWriteFilter.java
  src/main/java/coffeandcommit/crema/domain/review/service/ReviewService.java
  src/main/java/coffeandcommit/crema/global/httpTest/GuideMeService.http
  src/main/java/coffeandcommit/crema/global/httpTest/GuidesAndReviews.http
  src/main/resources/application-local.yml
Labels: 성능 개선

#154 [Fix] 공유파일업로드 로직 수정
  src/main/java/coffeandcommit/crema/domain/videocall/controller/VideoCallFileController.java
  src/main/java/coffeandcommit/crema/domain/videocall/service/VideoCallFileService.java
Labels: 버그

#153 [Fix] 멤버에서 가이드 업그레이드에서 업로드한 pdf 조회 시 presigned url 사용하게 변경
  src/main/java/coffeandcommit/crema/domain/member/service/MemberService.java
  src/test/java/coffeandcommit/crema/domain/member/controller/MemberControllerTest.java
  src/test/java/coffeandcommit/crema/domain/member/service/MemberCoffeeChatServiceTest.java
  src/test/java/coffeandcommit/crema/domain/member/service/MemberServiceTest.java
Labels: 버그

#157 [feat] access 토큰 유효시간 만료 시 refresh 토큰 기반 자동갱신되게 수정
  src/main/java/coffeandcommit/crema/global/auth/jwt/JwtAuthenticationFilter.java
Labels: 기능 개발

#166 [Fix] 화상통화 QuickJoin 에러 수정
  src/main/java/coffeandcommit/crema/domain/reservation/repository/ReservationRepository.java
  src/main/java/coffeandcommit/crema/domain/videocall/controller/VideoCallController.java
  src/main/java/coffeandcommit/crema/domain/videocall/entity/VideoSession.java
  src/main/java/coffeandcommit/crema/domain/videocall/repository/VideoSessionRepository.java
  src/main/java/coffeandcommit/crema/domain/videocall/service/VideoCallService.java
Labels: 버그

#170 [fix] 프론트 버그 해결 (가이드 업그레이드 로직에서 퇴사일 검증, access token 자동 재발급)
  member-load-test.js
  src/main/java/coffeandcommit/crema/domain/member/service/MemberService.java
  src/main/java/coffeandcommit/crema/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/coffeandcommit/crema/global/auth/service/AuthService.java
  src/main/java/coffeandcommit/crema/global/auth/util/CookieUtil.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/test/java/coffeandcommit/crema/global/auth/jwt/JwtAuthenticationFilterTest.java
  src/test/java/coffeandcommit/crema/global/auth/service/AuthServiceTest.java
Labels: 버그
