Repository Coffee-Commit/Crema_Backend, pull requests merged in 2025-08, with the labels that each got.

#5 feat: Exception 관련 기능 구현
  src/main/java/coffeandcommit/crema/global/common/exception/BaseException.java
  src/main/java/coffeandcommit/crema/global/common/exception/ExceptionController.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/BaseCode.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/SuccessStatus.java
  src/main/java/coffeandcommit/crema/global/common/exception/handler/GlobalExceptionHandler.java
  src/main/java/coffeandcommit/crema/global/common/exception/response/ApiResponse.java
  src/main/java/coffeandcommit/crema/global/common/exception/response/ErrorResponse.java
Labels: 기능 개발

#15 [ Fix] exception 관련 run time 에러 & build.gradle, application.yml의 aws 에러 해결
  .gitignore
  build.gradle
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/main/java/coffeandcommit/crema/global/common/exception/handler/GlobalExceptionHandler.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 버그

#16 [Feat] OAuth2 로그인(카카오, 구글) & member 도메인 crud 구현 + security config 작성
  build.gradle
  gradlew
  src/main/java/coffeandcommit/crema/CremaApplication.java
  src/main/java/coffeandcommit/crema/domain/member/controller/MemberController.java
  src/main/java/coffeandcommit/crema/domain/member/dto/response/MemberResponse.java
  src/main/java/coffeandcommit/crema/domain/member/entity/Member.java
  src/main/java/coffeandcommit/crema/domain/member/enums/MemberRole.java
  src/main/java/coffeandcommit/crema/domain/member/mapper/MemberMapper.java
  src/main/java/coffeandcommit/crema/domain/member/repository/MemberRepository.java
  src/main/java/coffeandcommit/crema/domain/member/service/MemberService.java
  src/main/java/coffeandcommit/crema/global/auth/config/SecurityConfig.java
  src/main/java/coffeandcommit/crema/global/auth/controller/AuthController.java
  src/main/java/coffeandcommit/crema/global/auth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/coffeandcommit/crema/global/auth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/coffeandcommit/crema/global/auth/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/coffeandcommit/crema/global/auth/jwt/JwtAuthenticationFilter.java
  src/main/java/coffeandcommit/crema/global/auth/jwt/JwtTokenProvider.java
  src/main/java/coffeandcommit/crema/global/auth/provider/GoogleOAuth2UserInfo.java
  src/main/java/coffeandcommit/crema/global/auth/provider/KakaoOAuth2UserInfo.java
  src/main/java/coffeandcommit/crema/global/auth/provider/OAuth2UserInfo.java
  src/main/java/coffeandcommit/crema/global/auth/service/AuthService.java
  src/main/java/coffeandcommit/crema/global/auth/service/CustomOAuth2User.java
  src/main/java/coffeandcommit/crema/global/auth/service/CustomOAuth2UserService.java
  src/main/java/coffeandcommit/crema/global/auth/service/CustomUserDetails.java
  src/main/java/coffeandcommit/crema/global/auth/service/TokenBlacklistService.java
  src/main/java/coffeandcommit/crema/global/auth/util/CookieUtil.java
  src/main/java/coffeandcommit/crema/global/common/config/RedisConfig.java
  src/main/java/coffeandcommit/crema/global/common/entitiy/BaseEntity.java
  src/main/java/coffeandcommit/crema/global/common/exception/ExceptionController.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/main/java/coffeandcommit/crema/global/common/exception/response/ErrorResponse.java
  src/main/resources/application.yml
Labels: 기능 개발

#18 Feat: Dev 환경용 파이프라인 추가
  Jenkinsfile
Labels: 기능 개발

#21 Fix: Jenkins가 브랜치를 판단하지 못하는 문제 버그 버그를 해결
  Jenkinsfile
Labels: 버그

#28 엔티티 추가
  src/main/java/coffeandcommit/crema/domain/guide/entity/ExperienceDetail.java
  src/main/java/coffeandcommit/crema/domain/meeting/entity/MeetingRoom.java
  src/main/java/coffeandcommit/crema/domain/reservation/entity/Reservation.java
  src/main/java/coffeandcommit/crema/domain/reservation/enums/Status.java
  src/main/java/coffeandcommit/crema/domain/review/entity/Review.java
  src/main/java/coffeandcommit/crema/domain/review/entity/ReviewExperience.java
  src/main/java/coffeandcommit/crema/domain/survey/entity/Survey.java
Labels: 기능 개발

#30 [Feat] dev 서버 연결 + member 엔티티 변경
  src/main/java/coffeandcommit/crema/domain/member/controller/MemberController.java
  src/main/java/coffeandcommit/crema/domain/member/dto/response/MemberPublicResponse.java
  src/main/java/coffeandcommit/crema/domain/member/dto/response/MemberResponse.java
  src/main/java/coffeandcommit/crema/domain/member/entity/Member.java
  src/main/java/coffeandcommit/crema/domain/member/service/MemberProfileService.java
  src/main/java/coffeandcommit/crema/domain/member/service/MemberService.java
  src/main/java/coffeandcommit/crema/global/auth/config/SecurityConfig.java
  src/main/java/coffeandcommit/crema/global/common/exception/code/ErrorStatus.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: 리팩토링, 기능 개발

#31 [Feat] 테스트용 계정 생성/로그인/삭제 api 구현 + global/httpTest 패키지 생성
  src/main/java/coffeandcommit/crema/domain/member/repository/MemberRepository.java
  src/main/java/coffeandcommit/crema/global/auth/config/SecurityConfig.java
  src/main/java/coffeandcommit/crema/global/auth/controller/TestAuthController.java
  src/main/java/coffeandcommit/crema/global/httpTest/TestAuthController.http
Labels: 기능 개발

#39 [Bug] clean build에 환경 변수가 주입되지 않는 버그
  Jenkinsfile
Labels: 버그

#45 추가된 엔티티 수정
  src/main/java/coffeandcommit/crema/domain/guide/entity/ExperienceDetail.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/ExperienceGroup.java
  src/main/java/coffeandcommit/crema/domain/guide/entity/GuideExperience.java
Labels: 기능 개발

#46 QueryDSL 초기 세팅
  build.gradle
  src/main/java/coffeandcommit/crema/global/common/config/QueryDslConfig.java
Labels: 기능 개발
